/**
 * @file    http_server.h
 * @brief   e_server-style HTTP server on the WCH net stack (wchnet).
 *
 * Serves the bundled single-page site (User/web_assets.h, generated by
 * ../../e_server/build_web.py) plus the JSON API - the same contract as the
 * reference host backend in ../../e_server/server.c and the f7-demo
 * nucleo-f746/bare/eth_http_server port:
 *
 *   GET  /                 page, Content-Encoding: gzip
 *   GET  /api/leds         {"leds":[0]}          (real LED GPIO state, PA0)
 *   POST /api/leds         body {"leds":[0]}     -> applies to the LED
 *   GET  /api/adc          {"vrefint_mv":..,"temp_c":..,"ts":..}
 *   GET  /api/info         {"arch","lan_ip","public_ip":null,"geo":null,
 *                           "weather":null,"ts":..}
 *   GET  /public/<name>    raw image bytes (from the embedded_files[] table,
 *                          none embedded on this board)
 */
#ifndef __HTTP_SERVER_H__
#define __HTTP_SERVER_H__

#include "debug.h"

#define HTTP_SERVER_PORT   80

extern void http_server_init(void);
extern void http_server_serve(u8 socketid, u8 *buf, u32 len);

#endif
